/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shadowhunter230 (https://sketchfab.com/Shadowhunter230)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/enviromental-modeling-castle-42613e41dfd4486288d04fc90d5c473f
Title: Enviromental Modeling Castle
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Castle = (props) => {
  const { nodes, materials } = useGLTF(
    "/models/enviromental_modeling_castle.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-1.962, 0, -2.969]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bellows1_Leather_MAT_0.geometry}
            material={materials.Leather_MAT}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bellows1_Wooden_Texture_0.geometry}
            material={materials.Wooden_Texture}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bellows1_Metal_MAT_0.geometry}
            material={materials.Metal_MAT}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bellows1_Rope_MAT_0.geometry}
            material={materials.Rope_MAT}
          />
        </group>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked2_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-4, -0.086, -22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked3_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-2, -0.086, -20]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked7_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[6, -0.086, 16]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door6_Door_MAT_0.geometry}
          material={materials.Door_MAT}
          position={[-15, 10.982, -12.173]}
          scale={[1.08, 1.173, 0.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked8_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-8, -0.086, 6]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway35_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-5, -0.079, -4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door5_Door_MAT_0.geometry}
          material={materials.Door_MAT}
          position={[15, 10.982, -12.173]}
          scale={[1.08, 1.173, 0.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked9_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-6, -0.086, -6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway10_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway6_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, 6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway9_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway8_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, 4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway11_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, 2]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway39_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-7, -0.079, -4]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall4_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-15, 0, 8.979]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doorway7_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-4.357, 9.909, -11.622]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.844, 1, 1.655]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway33_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doorway4_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-11.622, 9.909, -20.222]}
          scale={[0.844, 1, 1.655]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway36_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-5, -0.079, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway32_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doorway5_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[18.378, 9.909, -20.222]}
          scale={[0.844, 1, 1.655]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_Portculius2_Wooden_Texture_0.geometry}
          material={materials.Wooden_Texture}
          position={[0, 0.764, -18.891]}
          scale={[0.912, 0.972, 0.912]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_Gateway4_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[0, 0, -19.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_Gateway3_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[0, 0, -15.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall2_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-18, 0, 15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked5_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[4, -0.086, 22]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked6_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-4, -0.086, 14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doorway2_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-4.357, 9.909, 18.378]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.844, 1, 1.655]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway42_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-11, -0.079, -6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway34_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-3, -0.079, -4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door2_Door_MAT_0.geometry}
          material={materials.Door_MAT}
          position={[-12.325, 11, 15.001]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.08, 1.173, 0.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doorway3_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-11.622, 9.909, 4.21]}
          scale={[0.844, 1, 1.655]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_tower_turret4_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[25, 0, -15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway41_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-9, -0.079, -6]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked12_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-12, -0.086, -4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked11_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-16, -0.086, 6]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked4_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-4, -0.086, -18]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door7_Door_MAT_0.geometry}
          material={materials.Door_MAT}
          position={[-15, 10.982, 12.156]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[1.08, 1.173, 0.259]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked10_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-14, -0.086, 6]}
          rotation={[0, Math.PI / 2, 0]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall6_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[15, 0, 1]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_Gate2_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[0, 0, -15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall9_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[0, 0, -15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall10_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-18, 0, -15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall8_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[15, 0, 19]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall7_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[15, 0, 10]}
          rotation={[0, Math.PI / 2, 0]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway37_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-5, -0.079, -6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway31_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -20]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway2_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway5_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway3_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, 10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway4_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, 8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway7_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, 6]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway38_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-7, -0.079, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway40_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-7, -0.079, -6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door3_Door_MAT_0.geometry}
          material={materials.Door_MAT}
          position={[-12.325, 11, -15]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.08, 1.173, 0.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door4_Door_MAT_0.geometry}
          material={materials.Door_MAT}
          position={[12.271, 11, -15]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.08, 1.173, 0.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doorway8_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[20.4, 9.89, -11.622]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.844, 1, 1.655]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Smithing_pit1_SLATE_MAT_0.geometry}
          material={materials.SLATE_MAT}
          position={[-11, 0.324, 1]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 0.324, 1.636]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wooden_Post1_Wooden_Texture_0.geometry}
          material={materials.Wooden_Texture}
          position={[-2.146, 1.543, 4.086]}
          scale={[0.251, 3.085, 0.251]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked1_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-2, -0.086, -24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_Gate1_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[0, 0, 15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall1_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[0, 0, 15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_Gateway1_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[0, 0, 14.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_Portculius1_Wooden_Texture_0.geometry}
          material={materials.Wooden_Texture}
          position={[0, 0.764, 13.109]}
          scale={[0.912, 0.972, 0.912]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door1_Door_MAT_0.geometry}
          material={materials.Door_MAT}
          position={[15, 10.982, 12.156]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[1.08, 1.173, 0.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway1_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, 12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway12_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway13_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway43_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-13, -0.079, -6]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_tower_turret2_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[25, 0, 15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall3_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-15, 0, 17.979]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_wall5_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-15, 0, -0.021]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_tower_turret3_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-5, 0, -15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doorway1_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[20.4, 9.89, 18.378]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.844, 1, 1.655]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_Gateway2_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[0, 0, 10.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castle_tower_turret1_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-5, 0, 15]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway16_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway14_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway18_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doorway6_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[18.378, 9.894, 4.21]}
          scale={[0.844, 1, 1.655]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway30_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -18]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway15_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway19_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway17_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway26_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -14]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway29_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -16]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway25_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway21_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -8]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway20_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -8]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway28_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -16]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway22_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway24_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[1, -0.079, -12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway23_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway27_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-1, -0.079, -14]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stone_pathway_cracked13_Stone_Bricks_MAT_0.geometry}
          material={materials.Stone_Bricks_MAT}
          position={[-18, -0.086, 6]}
          rotation={[0, Math.PI / 2, 0]}
        />
      </group>
    </group>
  );
};

export default Castle;

useGLTF.preload("/models/enviromental_modeling_castle.glb");
