/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Character Animated.glb -o src/Components/Character.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import { useControls } from "leva";

export function Character(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/Character Animated.glb"
  );
  const { actions } = useAnimations(animations, group);

  const { animation } = useControls("Sigismund Controls", {
    animation: { value: "Idle", options: Object.keys(actions) },
  });

  useEffect(() => {
    if (!actions || !actions[animation]) return;
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);

  useEffect(() => {
    actions["CharacterArmature|PickUp"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={35}
          >
            <primitive object={nodes.Root} />
          </group>
          <group
            name="Rogue"
            position={[0, 0, 0.166]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={35}
          >
            <skinnedMesh
              name="Rogue_1"
              geometry={nodes.Rogue_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Rogue_1.skeleton}
            />
            <skinnedMesh
              name="Rogue_2"
              geometry={nodes.Rogue_2.geometry}
              material={materials.UnderShirt}
              skeleton={nodes.Rogue_2.skeleton}
            />
            <skinnedMesh
              name="Rogue_3"
              geometry={nodes.Rogue_3.geometry}
              material={materials.Pants}
              skeleton={nodes.Rogue_3.skeleton}
            />
            <skinnedMesh
              name="Rogue_4"
              geometry={nodes.Rogue_4.geometry}
              material={materials.Shirt}
              skeleton={nodes.Rogue_4.skeleton}
            />
            <skinnedMesh
              name="Rogue_5"
              geometry={nodes.Rogue_5.geometry}
              material={materials.Detail}
              skeleton={nodes.Rogue_5.skeleton}
            />
            <skinnedMesh
              name="Rogue_6"
              geometry={nodes.Rogue_6.geometry}
              material={materials.Boots}
              skeleton={nodes.Rogue_6.skeleton}
            />
          </group>
          <skinnedMesh
            name="Rogue001"
            geometry={nodes.Rogue001.geometry}
            material={materials["Material.006"]}
            skeleton={nodes.Rogue001.skeleton}
            position={[0, 0, 0.166]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={35}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Character Animated.glb");
