// King by Quaternius (https://poly.pizza/m/I1gTjmuK2m)

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";

export function King(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/King.glb");
  const { actions } = useAnimations(animations, group);

  const { animation } = useControls("King Controls", {
    animation: { value: "", options: Object.keys(actions) },
  });

  useEffect(() => {
    if (!actions || !actions[animation]) return;
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);

  useEffect(() => {
    actions["CharacterArmature|Wave"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            name="King_Feet"
            geometry={nodes.King_Feet.geometry}
            material={materials.Metal}
            skeleton={nodes.King_Feet.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <group name="King_Legs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="King_Legs_1"
              geometry={nodes.King_Legs_1.geometry}
              material={materials.Metal}
              skeleton={nodes.King_Legs_1.skeleton}
            />
            <skinnedMesh
              name="King_Legs_2"
              geometry={nodes.King_Legs_2.geometry}
              material={materials.DarkBrown}
              skeleton={nodes.King_Legs_2.skeleton}
            />
            <skinnedMesh
              name="King_Legs_3"
              geometry={nodes.King_Legs_3.geometry}
              material={materials.Metal_Dark}
              skeleton={nodes.King_Legs_3.skeleton}
            />
          </group>
          <group name="King_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="King_Body_1"
              geometry={nodes.King_Body_1.geometry}
              material={materials.Metal}
              skeleton={nodes.King_Body_1.skeleton}
            />
            <skinnedMesh
              name="King_Body_2"
              geometry={nodes.King_Body_2.geometry}
              material={materials.Metal_Dark}
              skeleton={nodes.King_Body_2.skeleton}
            />
            <skinnedMesh
              name="King_Body_3"
              geometry={nodes.King_Body_3.geometry}
              material={materials.Blue}
              skeleton={nodes.King_Body_3.skeleton}
            />
            <skinnedMesh
              name="King_Body_4"
              geometry={nodes.King_Body_4.geometry}
              material={materials.Beige}
              skeleton={nodes.King_Body_4.skeleton}
            />
            <skinnedMesh
              name="King_Body_5"
              geometry={nodes.King_Body_5.geometry}
              material={materials.Skin}
              skeleton={nodes.King_Body_5.skeleton}
            />
          </group>
          <group name="King_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="King_Head_1"
              geometry={nodes.King_Head_1.geometry}
              material={materials.Skin}
              skeleton={nodes.King_Head_1.skeleton}
            />
            <skinnedMesh
              name="King_Head_2"
              geometry={nodes.King_Head_2.geometry}
              material={materials.Hair_White}
              skeleton={nodes.King_Head_2.skeleton}
            />
            <skinnedMesh
              name="King_Head_3"
              geometry={nodes.King_Head_3.geometry}
              material={materials.Eye}
              skeleton={nodes.King_Head_3.skeleton}
            />
            <skinnedMesh
              name="King_Head_4"
              geometry={nodes.King_Head_4.geometry}
              material={materials.Gold}
              skeleton={nodes.King_Head_4.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

export default King;

useGLTF.preload("/models/King.glb");
