/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: by__Rx (https://sketchfab.com/by__Rx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-knight-sculpture-game-ready-6cdd055b4afa41eb9360dbbfe75c7f10
Title: Medieval Knight | Sculpture | Game ready
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";
import { useFrame } from "@react-three/fiber";

const Knight = (props) => {
  const group = useRef();
  const { scene, animations, nodes, materials } = useGLTF(
    "/models/medieval_knight__sculpture__game_ready.glb"
  );
  const { actions, mixer } = useAnimations(animations, scene);

  useEffect(() => {
    const action = actions["mixamo.com"];
    if (action) {
      action.reset().fadeIn(0.5).play();
    }
  }, [actions]);

  useFrame((state, delta) => mixer?.update(delta));

  //   const { animation } = useControls("Knight Controls", {
  //     animation: { value: "mixamo.com", options: Object.keys(actions) },
  //   });
  //   console.log("animation", animation);

  //   useEffect(() => {
  //     if (!actions || !actions[animation]) return;
  //     actions[animation].reset().fadeIn(0.5).play();
  //     return () => actions[animation].fadeOut(0.5);
  //   }, [animation]);
  return (
    <group ref={group} {...props} object={scene} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.996}
        >
          <group
            name="985ec9739c20496b97be5cb1a0679ffbfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.007}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    name="Object_23"
                    geometry={nodes.Object_23.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <skinnedMesh
                    name="Object_27"
                    geometry={nodes.Object_27.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_27.skeleton}
                  />
                  <skinnedMesh
                    name="Object_29"
                    geometry={nodes.Object_29.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_29.skeleton}
                  />
                  <skinnedMesh
                    name="Object_31"
                    geometry={nodes.Object_31.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_31.skeleton}
                  />
                  <skinnedMesh
                    name="Object_33"
                    geometry={nodes.Object_33.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_33.skeleton}
                  />
                  <skinnedMesh
                    name="Object_35"
                    geometry={nodes.Object_35.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_35.skeleton}
                  />
                  <skinnedMesh
                    name="Object_37"
                    geometry={nodes.Object_37.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_37.skeleton}
                  />
                  <skinnedMesh
                    name="Object_39"
                    geometry={nodes.Object_39.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_39.skeleton}
                  />
                  <skinnedMesh
                    name="Object_41"
                    geometry={nodes.Object_41.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_41.skeleton}
                  />
                  <skinnedMesh
                    name="Object_43"
                    geometry={nodes.Object_43.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_43.skeleton}
                  />
                  <skinnedMesh
                    name="Object_45"
                    geometry={nodes.Object_45.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_45.skeleton}
                  />
                  <skinnedMesh
                    name="Object_47"
                    geometry={nodes.Object_47.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_47.skeleton}
                  />
                  <skinnedMesh
                    name="Object_49"
                    geometry={nodes.Object_49.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_49.skeleton}
                  />
                  <skinnedMesh
                    name="Object_51"
                    geometry={nodes.Object_51.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_51.skeleton}
                  />
                  <skinnedMesh
                    name="Object_53"
                    geometry={nodes.Object_53.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_53.skeleton}
                  />
                  <skinnedMesh
                    name="Object_55"
                    geometry={nodes.Object_55.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_55.skeleton}
                  />
                  <skinnedMesh
                    name="Object_57"
                    geometry={nodes.Object_57.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_57.skeleton}
                  />
                  <skinnedMesh
                    name="Object_59"
                    geometry={nodes.Object_59.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_59.skeleton}
                  />
                  <skinnedMesh
                    name="Object_61"
                    geometry={nodes.Object_61.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_61.skeleton}
                  />
                  <skinnedMesh
                    name="Object_63"
                    geometry={nodes.Object_63.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_63.skeleton}
                  />
                  <skinnedMesh
                    name="Object_65"
                    geometry={nodes.Object_65.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_65.skeleton}
                  />
                  <skinnedMesh
                    name="Object_67"
                    geometry={nodes.Object_67.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_67.skeleton}
                  />
                  <skinnedMesh
                    name="Object_69"
                    geometry={nodes.Object_69.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_69.skeleton}
                  />
                  <skinnedMesh
                    name="Object_71"
                    geometry={nodes.Object_71.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_71.skeleton}
                  />
                  <skinnedMesh
                    name="Object_73"
                    geometry={nodes.Object_73.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_73.skeleton}
                  />
                  <skinnedMesh
                    name="Object_75"
                    geometry={nodes.Object_75.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_75.skeleton}
                  />
                  <skinnedMesh
                    name="Object_77"
                    geometry={nodes.Object_77.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_77.skeleton}
                  />
                  <skinnedMesh
                    name="Object_79"
                    geometry={nodes.Object_79.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_79.skeleton}
                  />
                  <skinnedMesh
                    name="Object_81"
                    geometry={nodes.Object_81.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_81.skeleton}
                  />
                  <skinnedMesh
                    name="Object_83"
                    geometry={nodes.Object_83.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_83.skeleton}
                  />
                  <skinnedMesh
                    name="Object_85"
                    geometry={nodes.Object_85.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_85.skeleton}
                  />
                  <skinnedMesh
                    name="Object_87"
                    geometry={nodes.Object_87.geometry}
                    material={materials.blinn1}
                    skeleton={nodes.Object_87.skeleton}
                  />
                  <skinnedMesh
                    name="Object_89"
                    geometry={nodes.Object_89.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_89.skeleton}
                  />
                  <skinnedMesh
                    name="Object_91"
                    geometry={nodes.Object_91.geometry}
                    material={materials.blinn3}
                    skeleton={nodes.Object_91.skeleton}
                  />
                  <skinnedMesh
                    name="Object_93"
                    geometry={nodes.Object_93.geometry}
                    material={materials.blinn2}
                    skeleton={nodes.Object_93.skeleton}
                  />
                  <group name="Object_6" />
                  <group name="Object_8" />
                  <group name="Object_10" />
                  <group name="Object_12" />
                  <group name="Object_14" />
                  <group name="Object_16" />
                  <group name="Object_18" />
                  <group name="Object_20" />
                  <group name="Object_22" />
                  <group name="Object_24" />
                  <group name="Object_26" />
                  <group name="Object_28" />
                  <group name="Object_30" />
                  <group name="Object_32" />
                  <group name="Object_34" />
                  <group name="Object_36" />
                  <group name="Object_38" />
                  <group name="Object_40" />
                  <group name="Object_42" />
                  <group name="Object_44" />
                  <group name="Object_46" />
                  <group name="Object_48" />
                  <group name="Object_50" />
                  <group name="Object_52" />
                  <group name="Object_54" />
                  <group name="Object_56" />
                  <group name="Object_58" />
                  <group name="Object_60" />
                  <group name="Object_62" />
                  <group name="Object_64" />
                  <group name="Object_66" />
                  <group name="Object_68" />
                  <group name="Object_70" />
                  <group name="Object_72" />
                  <group name="Object_74" />
                  <group name="Object_76" />
                  <group name="Object_78" />
                  <group name="Object_80" />
                  <group name="Object_82" />
                  <group name="Object_84" scale={[1, 1, 1.011]} />
                  <group name="Object_86" />
                  <group
                    name="Object_88"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[0.259, 0.259, 0.401]}
                  />
                  <group name="Object_90" />
                  <group
                    name="Object_92"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[0.259, 0.259, 0.401]}
                  />
                  <group name="under_low" />
                  <group name="cheville_low" />
                  <group name="feet_low" />
                  <group name="up_low" />
                  <group name="leg_low" />
                  <group name="knee_low" />
                  <group name="wing01_low" />
                  <group name="wing02_low" />
                  <group name="attach_low" />
                  <group name="face_low" />
                  <group name="Helmet_low" />
                  <group name="Jaw_low" />
                  <group name="Mohawks_low" />
                  <group name="cross_low" />
                  <group name="Ears_low" />
                  <group name="Forhead_low" />
                  <group name="chest_low" />
                  <group name="bavet_low" />
                  <group name="neck_low" />
                  <group name="manche_low" />
                  <group name="strap_low" />
                  <group name="patch_low" />
                  <group name="elbow_low" />
                  <group name="chains02_low" />
                  <group name="arm_low" />
                  <group name="epaulette_low" />
                  <group name="shoulder_low" />
                  <group name="glove_low" />
                  <group name="hand_low" />
                  <group name="thumps_low" />
                  <group name="fingers_low" />
                  <group name="hips_low" />
                  <group name="sidepatch_low" />
                  <group name="donut_low" />
                  <group name="belt_low" />
                  <group name="chains_low" />
                  <group name="hold_low" />
                  <group name="o_low" />
                  <group name="short_low" />
                  <group name="robe_low" scale={[1, 1, 1.011]} />
                  <group name="bouclier_low" />
                  <group
                    name="twist_low"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[0.259, 0.259, 0.401]}
                  />
                  <group name="tickle_low" />
                  <group
                    name="twist01_low"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={[0.259, 0.259, 0.401]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/medieval_knight__sculpture__game_ready.glb");
export default Knight;
