/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Prozone (https://sketchfab.com/Furnitures)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/princess-nun-royal-queen-74b7fd7e20db45438ca7516911257c89
Title: Princess Nun Royal Queen
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Princess = (props) => {
  const { nodes, materials } = useGLTF("/models/princess_nun_royal_queen.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.014}>
        <group position={[0, 49.953, -0.125]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.desirefxme_002_down_0.geometry}
            material={materials.down}
            position={[0, -0.125, -49.953]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.desirefxme_003_head_0.geometry}
            material={materials.head}
            position={[0, -0.125, -49.953]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={10}
          />
        </group>
      </group>
    </group>
  );
};

export default Princess;

useGLTF.preload("/models/princess_nun_royal_queen.glb");
